<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="1564" started-at="2018-08-15T07:48:53Z" finished-at="2018-08-15T07:48:55Z">
    <groups>
    </groups>
    <test name="test12" duration-ms="1564" started-at="2018-08-15T07:48:53Z" finished-at="2018-08-15T07:48:55Z">
      <class name="post.TestHttpPostData">
        <test-method status="PASS" signature="getCatalogueTest(java.lang.String, java.lang.String)[pri:0, instance:post.TestHttpPostData@28d25987]" name="getCatalogueTest" duration-ms="1298" started-at="2018-08-15T15:48:54Z" data-provider="getCatalogue" finished-at="2018-08-15T15:48:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://172.16.8.113/api/rdos/batch/batchCatalogue/getCatalogue]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{"catalogueType":"TaskDevelop","isGetFile":true,"nodePid":207}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCatalogueTest -->
        <test-method status="FAIL" signature="addCatalogueTest(java.lang.String, java.lang.String)[pri:0, instance:post.TestHttpPostData@28d25987]" name="addCatalogueTest" duration-ms="91" started-at="2018-08-15T15:48:55Z" data-provider="addCatalogue" finished-at="2018-08-15T15:48:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://172.16.8.113/api/rdos/batch/batchCatalogue/addCatalogue]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{"nodeName":"aaasaqq","nodePid":205}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at post.HttpRequestPost.httpPostData(HttpRequestPost.java:48)
	at post.TestHttpPostData.addCatalogueTest(TestHttpPostData.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCatalogueTest -->
      </class> <!-- post.TestHttpPostData -->
    </test> <!-- test12 -->
  </suite> <!-- Suite1 -->
</testng-results>
